
#  Dockerfile 1

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

# Accept dynamic argument
ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}

# Set environment=development
ENV ENVIRONMENT=production

COPY . .

CMD ["node", "app.js"]