# Each instruction in this file generates a new layer that gets pushed to your local image cache
# The linen below stats we weill base our new image on the latest official ubuntu
FROM ubuntu:latest

# Identify the maintainer of an image

LABEL version="0.0.1"
LABEL maintainer="kchaudhary@e-works.co.uk"

# Update the image to the latest packages
RUN apt-get update && apt-get upgrade -y

# Install NGINX to test.
RUN apt-get install nginx -y

# Expose port 80
EXPOSE 80

# Last is the actual command to start up NGINX within our Container 
CMD ["nginx", "-g", "daemon off;"]
